### ISSUE TITLE
Remove colors

### ISSUE THREAD

**Issue by Aymkdn** [zeeshanu/dumper.js#15]
Hey,

Is there an option to remove the colors ?

I'd like to use it within the browser, in the Web Console. However the colors appear as the below:
```
[1m[30mobject[39m[22m (size=7) {
    'listname' => [36mstring[39m [31m"Assets"[39m (length=6)
```

Thanks

**Comment by Aymkdn** [comment]
In the meantime, I've installed [`strip-ainsi`](https://github.com/chalk/strip-ansi) and I call it [there](https://github.com/zeeshanu/dumper.js/blob/master/src/dumper.js#L60)

**Comment by zeeshanu** [comment]
Hi @Aymkdn 
Thanks for opening the issue, but this is not meant to be used in the browser.

**Comment by mtompkins** [comment]
I agree that the ability to remove colors would be beneficial.
