### ISSUE TITLE
Its the little things in life..

### ISSUE THREAD

**Issue by mikeerickson** [zeeshanu/dumper.js#16]
I am guessing you are (were) a Laravel dev, I always recreate this function in my various JS apps.  Now I will just let this project do the job.

Thanks :-)

**Comment by zeeshanu** [comment]
Yes, you guessed it right.
Glad you liked it :)

**Comment by shalvah** [comment]
Awesome project here. Would be cool to add a little note to say it was inspired by the Laravel helper.
